name: thoth
channels:
  - anaconda
  - conda-forge
dependencies:
  - python>3.7
  - numpy
  - scikit-learn
  - pandas
  - matplotlib
  - jupyterlab
  - bokeh
  - pyyaml
  - requests
  - wikipedia
  - nltk
  - gensim
  - pyemd
  - xgboost
  - graphviz
